doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Security:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules/Security/Entity'
                prefix: 'App\Modules\Security\Entity'
                alias: Security
            Remembrall:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules/Remembrall/Entity'
                prefix: 'App\Modules\Remembrall\Entity'
                alias: Remembrall
