controllers:
    resource: ../../src/Controller/
    type: annotation

security.controllers:
    resource: ../../src/Modules/Security/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
