monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
        grouped:
            type: group
            members: [ rotating_file, symfony_mailer ]
        rotating_file:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [ "!event" ]
            max_files: 10
        symfony_mailer:
            type: symfony_mailer
            from_email: '%env(string:MAIL_FROM)%'
            to_email: '%env(string:ADMIN_MAIL)%'
            subject: 'Błąd na przypomijance! %%message%%'
            level: debug
            formatter: monolog.formatter.html
            content_type: text/html
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
